# Site settings
title: Romano Schabalala
email: rschabalala@gmail.com
description: > # My portfolio website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username: rschabalala
github_username: Mrschabs

# Build settings
markdown: kramdown
